name: Curseforge
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install --location=global wow-curse-tools
      - run: wct publish --token ${{ secrets.CURSE_TOKEN }}