on:
  push:
    tags:
      - v*

jobs:
  job:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: BigWigsMods/packager@v2
